services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '3000:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # Mount local folder with init scripts
    restart: unless-stopped
    
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -p 5432']
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: my-pgweb
    ports:
      - '8081:8081' # Access pgweb at localhost:8081
    environment:
      - PGWEB_DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - db # Wait for the database to start
    restart: unless-stopped

volumes:
  postgres-data:
